### PR TITLE
Adding support to FCM and change packagename for npm (ignore package.json)

### PR DESCRIPTION
**Pull request by oscar-anton**
The android client can't receive a notification via FCM because the addNotification method was missing.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
Can you add some tests to verify your changes and prevent regressions in the future?

**Comment by Amir-61** [comment]
@oscar-anton Any update on this?

**Comment by zbarbuto** [comment]
The repository name and url probably shouldn't change as part of this PR

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by bajtos** [comment]
Closing as abandoned.

**Pull request closed without merging**
