### PR TITLE
Support mutableContent for rich notification

### PR DESCRIPTION
**Pull request by ht22pt**
### Description

Support mutableContent for rich notification.

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by ht22pt** [comment]
Support #169

**Comment by ht22pt** [comment]
.ok\W+to\W+test.

**Pull request closed without merging**
