### PR TITLE
translation return for Q4 drop1

### PR DESCRIPTION
**Pull request by candytangnb**
translation return for Q4 drop1

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by dhmlau** [comment]
@slnode test please

**Pull request merged**
