### PR TITLE
update dependencies and support for priority in GCM

### PR DESCRIPTION
**Pull request by behrad**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
Hi @behrad, thank you for the pull request. We need you to sign our CLA before we can accept your contribution. See https://cla.strongloop.com/agreements/strongloop/loopback-component-push

**Comment by behrad** [comment]
DONE @bajtos

**Comment by bajtos** [comment]
Thank you. I am seeing test errors on our CI, could you please run `npm test` on your machine and fix all errors reported? I suspect that the upgrade of dependencies may have broken assumptions made in this module.

**Comment by behrad** [comment]
tests are failing, I will check whats happening...

**Comment by bajtos** [comment]
@behrad ping, what's the status of this pull request? Are you still keen to finish this patch?

**Comment by behrad** [comment]
updating apn & gcm modules to recent versions causes this module some problems, I've planned to update the code to make tests pass...

**Comment by bajtos** [comment]
Hi @behrad, please leave a message when you are done with the changes - GH does not send any notifications for new commits, thus I didn't know this is ready for another review.

The current patch mixes too many things together, which makes future code archaeology difficult. Please split it into multiple standalone changes and send these changes as individual pull requests. Please mention my handle @bajtos in the description of these PRs, so that I get notification.

At minimum, send the APNS-related changes in one pull request, move wns implementation to a new PR too and then keep this PR focused on adding support for `priority` to GCM only.

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by superkhau** [comment]
@bajtos This PR is a year old, I want to close this PR as stale but wanted to get your feedback since you worked on it for awhile. Is it still relevant?

@behrad Are you still working on this PR? Is it safe to close or would you like to rebase/update the changes and continue?

**Comment by bajtos** [comment]
Let's close it, it needs to be split into smaller chunks anyways (see https://github.com/strongloop/loopback-component-push/pull/97#issuecomment-174510992).

**Pull request closed without merging**
