### PR TITLE
Support APNs & HTTP/2 through new node-apn version

### PR DESCRIPTION
**Pull request by iliraga**
What I did is
- ditch the whole feedback service
- ditchthe whole certificate relevant service
- implemented the connection through the new apn provider-object
- implemented the "devicesGone"-functionality with the new apple feedback system
- following the [fellow boyscout rule](http://deviq.com/boy-scout-rule/), refactored and commented some stuff in the apns part.
- Changed unit tests and ditched the whole certificate-relevant part

note: this is the second pull request for this particular feature. The first one had too much commits and was not rebase-able anymore. Second try. See PR #133

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by iliraga** [comment]
@superkhau here we go

**Comment by superkhau** [comment]
@raymondfeng PTAL, you already reviewed parts of this in another PR but @iliraga cleaned up some of it before landing.

**Comment by superkhau** [comment]
@slnode test please

**Comment by superkhau** [comment]
Landing since CI is green.

**Comment by superkhau** [comment]
@iliraga Thanks for the contribution! :bowing_man:

**Pull request merged**
