### PR TITLE
Fix timeout in tests on Windows [1.x]

### PR DESCRIPTION
**Pull request by bajtos**
Rework the test waiting for connection failure to periodically check whether the error has been reported yet, instead of having a constant timeout value.

See also #135 that fixed the CI on `master`.

cc @superkhau

### CODE REVIEW

**Comment by bajtos** [comment]
The Node v0.10 failure is unrelated:

```

D:\t\t1097085489204056866dirbfr\node_modules\build-framework\node_modules\mocha-jenkins-reporter\lib\jenkins.js:259
    var n = ++currentSuite.failures;
                          ^
TypeError: Cannot read property 'failures' of null
    at Runner.<anonymous> (D:\t\t1097085489204056866dirbfr\node_modules\build-framework\node_modules\mocha-jenkins-reporter\lib\jenkins.js:259:27)
    at Runner.emit (events.js:117:20)
    at Runner.fail (D:\workspace\loopback-component-push\b88abec9\node_modules\mocha\lib\runner.js:233:8)
```

I think we should start removing Node v0.10 from our CI builds, what do you think @rmg and @superkhau?

**Comment by superkhau** [comment]
@bajtos Thanks for fixing the windows issues. :clap:

WIth regard to removing CI builds, yes we should removing it ASAP. We're just wasting time working on those issues now IMO. You also sent the notification on GG announcement regarding the dropping -- did you hear anything back yet?

**Comment by bajtos** [comment]
> You also sent the notification on GG announcement regarding the dropping -- did you hear anything back yet?

No, see https://groups.google.com/forum/#!topic/loopbackjs/b9MCPOHrUgk The post got only 21 views, looks like there are not many people watching the mailing list.

**Comment by superkhau** [comment]
The GG post wasn't pinned to the top (I pinned it now for you), so that would probably mean less views.

> The post got only 21 views, looks like there are not many people watching the mailing list.

We gotta do something about that. ;) I don't blame them though because we haven't really been responding promptly there IMO.

**Pull request merged**
