### PR TITLE
FIX #82 - alert and badge are not included in GCM pushes

### LINKED ISSUE #82: Using `alert` property in android pushes doesn't work
Caused by `alert` not being an enumerable property on `Notification`.

Workaround is:
```
 Object.defineProperty(notification, 'alert', {
  value: notification.alert,
  writable: true,
  enumerable: true,
  configurable: true
});
```

### PR DESCRIPTION
**Pull request by seriousben**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by seriousben** [comment]
Fixes #82

**Comment by seriousben** [comment]
Fixes #106

**Comment by seriousben** [comment]
Ready to be merged

**Comment by superkhau** [comment]
@seriousben Can you fix the conflicts on this PR and run the linter too? Other than that, the changes LGTM.

@raymondfeng PTAL to make sure I didn't miss anything.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by seriousben** [comment]
@superkhau Done! Thanks for the reminder.

**Comment by seriousben** [comment]
@superkhau Ready to be merged

**Comment by superkhau** [comment]
@seriousben Thanks for the contribution! :+1:

**Pull request merged**
