### PR TITLE
Use eslint in favour of JSHint

### PR DESCRIPTION
**Pull request by superkhau**
@Amir-61 @gunjpan PTAL

### CODE REVIEW

**Comment by gunjpan** [comment]
@slnode test please

**Comment by superkhau** [comment]
Unrelated windows failures, gonna land this and backport.

**Comment by gunjpan** [comment]
@superkhau: For future reference, could you please squash commits to single commit before merging. Thanks.

**Comment by superkhau** [comment]
@gunjpan It was squashed when landing already, https://github.com/strongloop/loopback-component-push/commit/73ab3a5478e2c6ff1ffd90652615d8681a199d08. Is that what you're talking about?

**Comment by gunjpan** [comment]
@superkhau : yeah. Weird that GH shows 3 commits, see:
screen shot 2016-10-13 at 4 01 49 pm

**Comment by superkhau** [comment]
Because I used the "squash" button on the GH UI. I believe it leaves the original intact.

**Pull request merged**
