### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jeveloper**
Correcting link to examples for backend, ios and android

#### Related issues

- connect to <link_to_referenced_issue>

### Checklist

- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by jeveloper** [comment]
I've signed an agreement to contribute. There is another thing that's not well documented with this library. a few items actually

**Comment by dhmlau** [comment]
@slnode test please

**Comment by dhmlau** [comment]
@jeveloper , thanks for your contribution.  Your PR has landed!

**Pull request merged**
