### PR TITLE
[SEMVER-MINOR] Update GCM, APN and node-cache

### PR DESCRIPTION
**Pull request by seriousben**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by raymondfeng** [comment]
ok to test

**Comment by seriousben** [comment]
I propose a major bump for this.

**Comment by seriousben** [comment]
@raymondfeng - Would be nice to get this merged in and release if possible. There are some crashes happening happening right now that APN has fixed a while back.

Also, would be nice to take opportunity of merging https://github.com/strongloop/loopback-component-push/pull/114 as well.

Thanks a lot!

**Comment by seriousben** [comment]
@raymondfeng This is ready to be merged

**Comment by seriousben** [comment]
We are using this branch in production without issues.

**Comment by superkhau** [comment]
@raymondfeng Leaving this one to your approval and merging.

**Comment by seriousben** [comment]
@raymondfeng Do you want me to change anything in this? Otherwise this is good to merge.

**Comment by seriousben** [comment]
@superkhau is there any way to get this reviewed faster?

**Comment by superkhau** [comment]
@bajtos Do you know enough about this component to review this PR?

**Comment by bajtos** [comment]
The code change LGTM.

> I think a major bump would be best for this change. Since there are lots of changes within GCM and APN.

This confuses me a bit. I don't see any obvious breaking changes, the API provided by the push components stays the same AFAICT. What did I miss? If there are no breaking changes, then I'd like to release this as a minor version.

**Comment by bajtos** [comment]
@seriousben could you please squash the commits into a single one (`git rebase -i master && git push -f`) and reword the commit message to follow [50/72 rule](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html)?

**Comment by seriousben** [comment]
@bajtos - This PR should be good to go.
Also you are right it is backward compatible. (I meant to say minor version bump.)

**Comment by seriousben** [comment]
@bajtos I am not sure why cis-jenkins failed.

**Comment by seriousben** [comment]
@bajtos this is ready to be merged.

**Comment by bajtos** [comment]
Landed, thank you for the contribution!

**Pull request merged**
