### PR TITLE
added sound and icon to FCM notification

### PR DESCRIPTION
**Pull request by r-antolin**
#### Related issues

- None

### Checklist

- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the [style
  guide](http://loopback.io/doc/en/contrib/style-guide.html)

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by r-antolin** [comment]
.ok\W+to\W+test.

**Comment by bajtos** [comment]
Thank you for the pull request. I think this issue should have been already fixed by #151.

**Pull request closed without merging**
