### PR TITLE
set userId as foreignKey

### PR DESCRIPTION
**Pull request by ningsuhen**
Currently, the userId field is a string which has problem in using the relation user.installations. Can we change this to an objectId instead?

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ningsuhen** [comment]
This will probably break existing models, let me know if there's a solution for backward compatibility.

**Comment by bajtos** [comment]
@ningsuhen thank you for the pull request, please fix the text indentation to use 2 space characters.

> This will probably break existing models

Can you elaborate more on this? It seems to my that this change should not break anything.

Is there any easy way how to write an automated test to verify that the change works as intended?

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by bajtos** [comment]
@ningsuhen also the patch no longer merges cleanly, please rebase it on top of the latest master.

**Comment by ningsuhen** [comment]
Originally the userId was stored as String in MongoDB. After the change, it is stored as ObjectId. As a result it might have unexpected results. I'll test this in detail and fix the indentation.

**Comment by bajtos** [comment]
Hi @ningsuhen, what's the status of this pull request? Are you still keen to finish it?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by ningsuhen** [comment]
Hi @bajtos, userId is used as a string even in documentation which will have to be updated. - http://docs.strongloop.com/display/public/LB/Push+notifications;jsessionid=75002F30D7BCD45E8E0D478D9A08AD9B. So, A better solution is to override this by extending the Installation model. 
e.g.
```json
{
  "name": "installation",
  "base": "Installation",
  "properties": {},
  "relations": {
    "user": {
      "type": "belongsTo",
      "model": "user",
      "foreignKey": "userId"
    }
  },
  "acls":[]
}
```
I'll close this for now.

**Pull request closed without merging**
