### PR TITLE
Pass contentAvailable through to APNS

### PR DESCRIPTION
**Pull request by jmah**

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@jmah thank you for the pull request. Is there a reasonably easy way how to test the added functionality?

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by bajtos** [comment]
@slnode ok to test

**Comment by jmah** [comment]
I just tested via debugger / console logs that the APNS library saw content-available, but I will look at adding it to unit tests tomorrow.

**Comment by jmah** [comment]
Not quite "tomorrow" but tests added for APS payload keys here: https://github.com/argon/node-apn/blob/master/lib/notification.js#L470

Also added `url-args`.

**Comment by bajtos** [comment]
I have simplified the test a bit (removed all notification fields that are not needed in the test), rebased the patch on top of the current master and landed via  bd6d711. Thank you for the contribution!

**Pull request closed without merging**
