### PR TITLE
Support for APNs HTTP/2 and new node-apn version

### PR DESCRIPTION
**Pull request by iliraga**
What I did is
- ditch the whole feedback service
- ditchthe whole certificate relevant service
- implemented the connection through the new apn provider-object
- implemented the "devicesGone"-functionality with the new apple feedback system
- following the [fellow boyscout rule](http://deviq.com/boy-scout-rule/), refactored and commented some stuff in the apns part.
- Changed unit tests and ditched the whole certificate-relevant part

What is left to do on this particular thing is:
- Make sure there is not a new connection each time there are notifications sent (this is an issue with node-apn, see [here](https://github.com/node-apn/node-apn/issues/454) and [here](https://github.com/node-apn/node-apn/issues/449))

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by iliraga** [comment]
any update on this pull request?

**Comment by raymondfeng** [comment]
ok to test

**Comment by raymondfeng** [comment]
There is an issue related to `eslint` that we need to fix.

Your PR looks good to me. Would you like to fix https://github.com/strongloop/loopback-example-push with http2 based apn too?

**Comment by superkhau** [comment]
@iliraga Please see https://github.com/strongloop/loopback-component-push/pull/134#issuecomment-260779376.

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by iliraga** [comment]
@superkhau I have changed the stuff requested by review and fixed an important bug as well. Now everything should be ready do integrate.

**Comment by superkhau** [comment]
@iliraga Can you fix the errors CI is complaining about?

1. PR Linter -- Your PR is out of date and needs to be rebased with master
2. Commit Linter -- Some commit messages are too long, see http://loopback.io/doc/en/contrib/git-commit-messages.html.

**Comment by iliraga** [comment]
Would be glad if someone could assist me with rebasing... Just spent two hours rebasing and the CI is still complaining.

**Comment by superkhau** [comment]
@iliraga Can you break this out into smaller sets of PRs for review? I checked out your code for rebasing and its conflicting everywhere.

I suggest checking out master and cherry-picking only relevant parts of code (and squashing down to single commits per feature). We can try landing this in pieces to speed up the process. Maybe even separate PRs entirely for each feature instead of 100 commits.

**Comment by iliraga** [comment]
@superkhau I will create a new pull request within next week with less commits, try to reuse the same changes.
Until then this pull request can be closed I think.

**Comment by superkhau** [comment]
@iliraga TY, just ping me again when you have the smaller PRs ready for review and let's land them. Your contributions look good. ;)

**Pull request closed without merging**
